[project]
name = "loader"
version = "0.1.0"
requires-python = "==3.11.*"
dependencies = [
    "core",
    "ml_core",
    "boto3==1.43.69",
    "pandas>=2.2.0,<3.0.0",
    "pyarrow>=25.0.1",
    "shapely>=2.1.2",
    "psycopg[binary]>=3.1.0",
    "pyyaml>=6.0.3",
]

[tool.uv]
package = false

[tool.uv.sources]
core = { path = "../libs/core", editable = true }
ml_core = { path = "../libs/ml_core", editable = true }

[dependency-groups]
dev = [
    "moto[s3]>=5.2.2",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
