[project]
name = "airflow"
version = "0.1.0"
requires-python = "==3.11.*"
dependencies = [
    "apache-airflow[postgres]>=3.0,<4",
    "apache-airflow-providers-standard",
]

[tool.uv]
package = false

[tool.uv.sources]
ml_common = { path = "../libs/ml_common", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
